runtime: go
api_version: go1.8
env: standard
threadsafe: true
instance_class: F1

service: go-task-sample

handlers:
- url: /.*
  script: _go_app
- url: /register/.*
  script: _go_app
  login: admin
- url: /worker/.*
  script: _go_app
  login: admin

includes:
- ../secret.yaml
