cron:
- description: "beego"
  url: /beego/cron
  target: api
  schedule: every 10 minutes
  timezone: Asia/Tokyo
  retry_parameters:
    job_retry_limit: 1
    min_backoff_seconds: 5
    max_doublings: 5
