runtime: go
api_version: go1.8
env: standard
threadsafe: true
instance_class: F1

service: go-api-sample

handlers:
- url: /.*
  script: _go_app
  secure: always

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /img
  static_dir: static/img

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

nobuild_files:
- src/gopkg.in
- src/golang.org

includes:
- ../secret.yaml

